[package]
name = "callora-cross-contract-tests"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
name = "callora_cross_contract_tests"
path = "src/mod.rs"
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
callora-settlement = { path = "../settlement" }
callora-revenue-pool = { path = "../revenue_pool" }
callora-vault = { path = "../vault" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
rand = "0.8"
